plot_RT_r <- barChart(RT_r.df,RT_r.df$representation,nbTechs = 2, ymin = 2, ymax = 9, "", paste("[",datatype," data] ","Trial Completion Time in Seconds. Error Bars, 95% CIs",sep = ""))
plot_RT_r_diff <- barChart(RT_r_diff.df,RT_r_diff.df$ratio,nbTechs = 1, ymin = 0.85, ymax = 1.75, "", paste("[",datatype," data] ","Trial Completion Time Ratios. Error Bars, 95% CIs",sep = ""))
plot_RT_g <- barChart(RT_g.df,RT_g.df$granularity,nbTechs = 3, ymin = 2, ymax = 9, "", paste("[",datatype," data] ","Trial Completion Time in Seconds. Error Bars, 95% CIs",sep = ""))
plot_RT_g_diff <- barChart(RT_g_diff.df,RT_g_diff.df$ratio ,nbTechs = 3, ymin = 0.7, ymax = 2.7, "", paste("[",datatype," data] ","Trial Completion Time Ratios. Error Bars, 95% CIs",sep = ""))
plot_RT_t <- barChart(RT_t.df,RT_t.df$representation,nbTechs = 2, ymin = 2, ymax = 7.5, "", paste("[",datatype," data] ","Trial Completion Time in Seconds. Error Bars, 95% CIs",sep = ""))
plot_RT_t_diff <- barChart(RT_t_diff.df,RT_t_diff.df$ratio ,nbTechs = 1, ymin = 0.9, ymax = 1.6, "", paste("[",datatype," data] ","Trial Completion Time Ratios. Error Bars, 95% CIs",sep = ""))

plot_err_rate_r <- barChart(err_rate_r.df,err_rate_r.df$representation,nbTechs = 2, ymin = 0, ymax = 0.6, "", paste("[",datatype," data] ","Error Rate. Error Bars, 95% CIs",sep = ""))
plot_err_rate_r_diff <- barChart(err_rate_r_diff.df,err_rate_r_diff.df$ratio,nbTechs = 1, ymin = -0.19, ymax = 0.45, "", paste("[",datatype," data] ","Error Rate Pairwise Differences. Error Bars, 95% CIs",sep = ""))
plot_err_rate_g <- barChart(err_rate_g.df,err_rate_g.df$granularity,nbTechs = 3, ymin = 0, ymax = 0.6, "", paste("[",datatype," data] ","Error Rate. Error Bars, 95% CIs",sep = ""))
plot_err_rate_g_diff <- barChart(err_rate_g_diff.df,err_rate_g_diff.df$ratio,nbTechs = 3, ymin = -0.2, ymax = 0.4, "", paste("[",datatype," data] ","Error Rate Pairwise Differences. Error Bars, 95% CIs",sep = ""))
plot_err_rate_t <- barChart(err_rate_t.df,err_rate_t.df$representation,nbTechs = 2, ymin = 0, ymax = 0.25, "", paste("[",datatype," data] ","Error Rate. Error Bars, 95% CIs",sep = ""))
plot_err_rate_t_diff <- barChart(err_rate_t_diff.df,err_rate_t_diff.df$ratio,nbTechs = 1, ymin = -0.15, ymax = 0.15, "", paste("[",datatype," data] ","Error Rate Pairwise Differences. Error Bars, 95% CIs",sep = ""))

plot_err_r <- barChart(err_r.df,err_r.df$representation,nbTechs = 2, ymin = 0, ymax = 0.21, "", paste("[",datatype," data] ","Error Magnitude (% of data domain). Error Bars, 95% CIs",sep = ""))
plot_err_r_diff <- barChart(err_r_diff.df,err_r_diff.df$ratio,nbTechs = 1, ymin = -0.1, ymax = 0.06, "", paste("[",datatype," data] ","Error Magnitude Pairwise Differences. Error Bars, 95% CIs",sep = ""))
plot_err_g <- barChart(err_g.df,err_g.df$granularity,nbTechs = 3, ymin = 0, ymax = 0.21, "", paste("[",datatype," data] ","Error Magnitude (% of data domain). Error Bars, 95% CIs",sep = ""))
plot_err_g_diff <- barChart(err_g_diff.df,err_g_diff.df$ratio,nbTechs = 3, ymin = -0.08, ymax = 0.17, "", paste("[",datatype," data] ","Error Magnitude Pairwise Differences. Error Bars, 95% CIs",sep = ""))
plot_err_t <- barChart(err_t.df,err_t.df$representation,nbTechs = 2, ymin = 0, ymax = 0.17, "", paste("[",datatype," data] ","Error Magnitude (% of data domain). Error Bars, 95% CIs",sep = ""))
plot_err_t_diff <- barChart(err_t_diff.df,err_t_diff.df$ratio,nbTechs = 1, ymin = -0.1, ymax = 0.055,  "", paste("[",datatype," data] ","Error Magnitude Pairwise Differences. Error Bars, 95% CIs",sep = ""))

plot_compare_between_err_r <- barChart(compare_between_err_r.df,compare_between_err_r.df$representation,nbTechs = 2, ymin = 0, ymax = 0.6, "", paste("[",datatype," data] ","Error Magnitude (% of data domain). Error Bars, 95% CIs",sep = ""))
plot_compare_between_err_r_diff <- barChart(compare_between_err_r_diff.df,compare_between_err_r_diff.df$ratio,nbTechs = 1, ymin = -0.33, ymax = 0.1, "", paste("[",datatype," data] ","Error Magnitude Pairwise Differences. Error Bars, 95% CIs",sep = ""))
plot_compare_between_err_g <- barChart(compare_between_err_g.df,compare_between_err_g.df$granularity,nbTechs = 3, ymin = 0, ymax = 0.6, "", paste("[",datatype," data] ","Error Magnitude (% of data domain). Error Bars, 95% CIs",sep = ""))
plot_compare_between_err_g_diff <- barChart(compare_between_err_g_diff.df,compare_between_err_g_diff.df$ratio,nbTechs = 3, ymin = -0.01, ymax = 0.6, "", paste("[",datatype," data] ","Error Magnitude Pairwise Differences. Error Bars, 95% CIs",sep = ""))

plot_pref_r <- barChart(preference_CI.df,preference_CI.df$representation,nbTechs = 2, ymin = 0, ymax = 100, "", paste("[",datatype," data] ","Preference: Linear vs Radial. Error Bars, 95% CIs",sep = ""))
plot_conf_r <- barChart(conf_r.df,conf_r.df$representation,nbTechs = 2, ymin = 2, ymax = 5, "", paste("[",datatype," data] ","Self-Reported Confidence. Error Bars, 95% CIs",sep = ""))
plot_conf_r_diff <- barChart(conf_r_diff.df,conf_r_diff.df$ratio,nbTechs = 1, ymin = -1.5, ymax = 0, "", paste("[",datatype," data] ","Confidence pairwise differences. Error Bars, 95% CIs",sep = ""))

ggsave(plot = plot_RT_r, filename = paste(datatype,"_",paste(datatype,"_","plot_RT_r.png",sep = ""),sep = ""), device ="png", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_RT_r.png",sep = ""))
ggsave(plot = plot_RT_r_diff, filename = paste(datatype,"_","plot_RT_r_diff.png",sep = ""), device ="png", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_RT_r_diff.png",sep = ""))
ggsave(plot = plot_RT_g, filename = paste(datatype,"_","plot_RT_g.png",sep = ""), device ="png", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_RT_g.png",sep = ""))
ggsave(plot = plot_RT_g_diff, filename = paste(datatype,"_","plot_RT_g_diff.png",sep = ""), device ="png", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_RT_g_diff.png",sep = ""))
ggsave(plot = plot_RT_t, filename = paste(datatype,"_","plot_RT_t.png",sep = ""), device ="png", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_RT_t_diff.png",sep = ""))
ggsave(plot = plot_RT_t_diff, filename = paste(datatype,"_","plot_RT_t_diff.png",sep = ""), device ="png", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_RT_t_diff.png",sep = ""))
ggsave(plot = plot_err_r, filename = paste(datatype,"_","plot_err_r.png",sep = ""), device ="png", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_r.png",sep = ""))
ggsave(plot = plot_err_r_diff, filename = paste(datatype,"_","plot_err_r_diff.png",sep = ""), device ="png", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_r_diff.png",sep = ""))
ggsave(plot = plot_err_rate_r, filename = paste(datatype,"_","plot_err_rate_r.png",sep = ""), device ="png", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_rate_r.png",sep = ""))
ggsave(plot = plot_err_rate_r_diff, filename = paste(datatype,"_","plot_err_rate_r_diff.png",sep = ""), device ="png", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_rate_r_diff.png",sep = ""))
ggsave(plot = plot_err_g, filename = paste(datatype,"_","plot_err_g.png",sep = ""), device ="png", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_g.png",sep = ""))
ggsave(plot = plot_err_g_diff, filename = paste(datatype,"_","plot_err_g_diff.png",sep = ""), device ="png", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_g_diff.png",sep = ""))
ggsave(plot = plot_err_rate_g, filename = paste(datatype,"_","plot_err_rate_g.png",sep = ""), device ="png", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_rate_g.png",sep = ""))
ggsave(plot = plot_err_rate_g_diff, filename = paste(datatype,"_","plot_err_rate_g_diff.png",sep = ""), device ="png", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_rate_g_diff.png",sep = ""))
ggsave(plot = plot_err_t, filename = paste(datatype,"_","plot_err_t.png",sep = ""), device ="png", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_t.png",sep = ""))
ggsave(plot = plot_err_t_diff, filename = paste(datatype,"_","plot_err_t_diff.png",sep = ""), device ="png", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_t_diff.png",sep = ""))
ggsave(plot = plot_err_rate_t, filename = paste(datatype,"_","plot_err_rate_t.png",sep = ""), device ="png", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_rate_t.png",sep = ""))
ggsave(plot = plot_err_rate_t_diff, filename = paste(datatype,"_","plot_err_rate_t_diff.png",sep = ""), device ="png", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_rate_t_diff.png",sep = ""))
ggsave(plot = plot_pref_r, filename = paste(datatype,"_","plot_pref_r.png",sep = ""), device ="png", width = 8, height = 2, units = "in", dpi = 300)
print(paste(datatype,"_","plot_pref_r.png",sep = ""))
ggsave(plot = plot_conf_r, filename = paste(datatype,"_","plot_conf_r.png",sep = ""), device ="png", width = 8, height = 2, units = "in", dpi = 300)
print(paste(datatype,"_","plot_conf_r.png",sep = ""))
ggsave(plot = plot_conf_r_diff, filename = paste(datatype,"_","plot_conf_r_diff.png",sep = ""), device ="png", width = 8, height = 2, units = "in", dpi = 300)
print(paste(datatype,"_","plot_conf_r_diff.png",sep = ""))

ggsave(plot = plot_RT_r, filename = paste(datatype,"_","plot_RT_r.pdf",sep = ""), device ="pdf", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_RT_r.pdf",sep = ""))
ggsave(plot = plot_RT_r_diff, filename = paste(datatype,"_","plot_RT_r_diff.pdf",sep = ""), device ="pdf", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_RT_r_diff.pdf",sep = ""))
ggsave(plot = plot_RT_g, filename = paste(datatype,"_","plot_RT_g.pdf",sep = ""), device ="pdf", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_RT_g.pdf",sep = ""))
ggsave(plot = plot_RT_g_diff, filename = paste(datatype,"_","plot_RT_g_diff.pdf",sep = ""), device ="pdf", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_RT_g_diff.pdf",sep = ""))
ggsave(plot = plot_RT_t, filename = paste(datatype,"_","plot_RT_t.pdf",sep = ""), device ="pdf", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_RT_t_diff.pdf",sep = ""))
ggsave(plot = plot_RT_t_diff, filename = paste(datatype,"_","plot_RT_t_diff.pdf",sep = ""), device ="pdf", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_RT_t_diff.pdf",sep = ""))
ggsave(plot = plot_err_r, filename = paste(datatype,"_","plot_err_r.pdf",sep = ""), device ="pdf", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_r.pdf",sep = ""))
ggsave(plot = plot_err_r_diff, filename = paste(datatype,"_","plot_err_r_diff.pdf",sep = ""), device ="pdf", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_r_diff.pdf",sep = ""))
ggsave(plot = plot_err_rate_r, filename = paste(datatype,"_","plot_err_rate_r.pdf",sep = ""), device ="pdf", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_rate_r.pdf",sep = ""))
ggsave(plot = plot_err_rate_r_diff, filename = paste(datatype,"_","plot_err_rate_r_diff.pdf",sep = ""), device ="pdf", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_rate_r_diff.pdf",sep = ""))
ggsave(plot = plot_err_g, filename = paste(datatype,"_","plot_err_g.pdf",sep = ""), device ="pdf", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_g.pdf",sep = ""))
ggsave(plot = plot_err_g_diff, filename = paste(datatype,"_","plot_err_g_diff.pdf",sep = ""), device ="pdf", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_g_diff.pdf",sep = ""))
ggsave(plot = plot_err_rate_g, filename = paste(datatype,"_","plot_err_rate_g.pdf",sep = ""), device ="pdf", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_rate_g.pdf",sep = ""))
ggsave(plot = plot_err_rate_g_diff, filename = paste(datatype,"_","plot_err_rate_g_diff.pdf",sep = ""), device ="pdf", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_rate_g_diff.pdf",sep = ""))
ggsave(plot = plot_err_t, filename = paste(datatype,"_","plot_err_t.pdf",sep = ""), device ="pdf", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_t.pdf",sep = ""))
ggsave(plot = plot_err_t_diff, filename = paste(datatype,"_","plot_err_t_diff.pdf",sep = ""), device ="pdf", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_t_diff.pdf",sep = ""))
ggsave(plot = plot_err_rate_t, filename = paste(datatype,"_","plot_err_rate_t.pdf",sep = ""), device ="pdf", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_rate_t.pdf",sep = ""))
ggsave(plot = plot_err_rate_t_diff, filename = paste(datatype,"_","plot_err_rate_t_diff.pdf",sep = ""), device ="pdf", width = 8, height = 4, units = "in", dpi = 300)
print(paste(datatype,"_","plot_err_rate_t_diff.pdf",sep = ""))
ggsave(plot = plot_pref_r, filename = paste(datatype,"_","plot_pref_r.pdf",sep = ""), device ="pdf", width = 8, height = 2, units = "in", dpi = 300)
print(paste(datatype,"_","plot_pref_r.pdf",sep = ""))
ggsave(plot = plot_conf_r, filename = paste(datatype,"_","plot_conf_r.pdf",sep = ""), device ="pdf", width = 8, height = 2, units = "in", dpi = 300)
print(paste(datatype,"_","plot_conf_r.pdf",sep = ""))
ggsave(plot = plot_conf_r_diff, filename = paste(datatype,"_","plot_conf_r_diff.pdf",sep = ""), device ="pdf", width = 8, height = 2, units = "in", dpi = 300)
print(paste(datatype,"_","plot_conf_r_diff.pdf",sep = ""))
